In [1]:
import requests
from bs4 import BeautifulSoup
import uuid
import difflib
import html5lib
import time
import pandas as pd
from sqlalchemy import create_engine
import psycopg2
pd.options.mode.chained_assignment = None

In [2]:
player_index = pd.read_csv('../updated_datasets/player_index.csv')
player_index = player_index[player_index.columns[1:]]
player_index

                player                                  uuid
0     Hot Rod Williams  ca94dd3e-c3dc-4682-8c88-0ed654c9d074
1          Danny Ferry  4d2819b0-30c9-40f3-af49-4b950b0fad78
2           Mark Price  1a806ca8-ea9c-4690-8fe4-0b7d13c80d36
3       Brad Daugherty  ae75e1f9-765b-4cde-afbc-b5e9f18e0a26
4          Larry Nance  97054146-250e-4988-aff6-40ce7e6f6c4d
...                ...                                   ...
2819        Vit Krejci  9b06ee3b-d2b2-4e58-9689-a11051808fde
2820      Olivier Sarr  d09f39f5-e68c-4f3d-ba3c-1e7946491fcd
2821  Lindy Waters III  a2d20bf5-1dab-4cfc-80e6-e0c848d31e9e
2822       Rob Edwards  f388acbe-7951-43e5-8778-dab1019c1843
2823    Zavier Simpson  df1508b7-0c24-4d83-bf2b-81a1ace956a7

[2824 rows x 2 columns]

In [17]:
def season_totals(start_year, end_year):
    df_list = []
    for i in range(start_year + 1, end_year + 2):
        var_name = f'season_totals_{i - 1}'
        r = requests.get(f'https://www.basketball-reference.com/leagues/NBA_{i}_totals.html')
        if r.status_code == 200:
            soup = BeautifulSoup(r.content, 'html.parser')
            table = soup.find('table')
            test = pd.read_html(str(table))[0]
            
            #table cleaning
            test.columns = test.columns.str.lower()
            test = test[test['player'] != 'Player'].drop(columns=['rk'])
            test = test.replace('\*','',regex=True)
            test.fillna(0, inplace=True)
            globals()[var_name] = test.merge(player_index)
            df_list.append(globals()[var_name])
            print(f'{var_name} worked!')
            
        else:
            print(f'ERROR {r.status_code}')
        
        time.sleep(30)
        
    return df_list

In [21]:
df_list = season_totals(1996, 2021)

season_totals_1996 worked!
season_totals_1997 worked!
season_totals_1998 worked!
season_totals_1999 worked!
season_totals_2000 worked!
season_totals_2001 worked!
season_totals_2002 worked!
season_totals_2003 worked!
season_totals_2004 worked!
season_totals_2005 worked!
season_totals_2006 worked!
season_totals_2007 worked!
season_totals_2008 worked!
season_totals_2009 worked!
season_totals_2010 worked!
season_totals_2011 worked!
season_totals_2012 worked!
season_totals_2013 worked!
season_totals_2014 worked!
season_totals_2015 worked!
season_totals_2016 worked!
season_totals_2017 worked!
season_totals_2018 worked!
season_totals_2019 worked!
season_totals_2020 worked!
season_totals_2021 worked!

In [20]:
season_totals_1996[season_totals_1996['player'] == 'Reggie Miller']

,player,pos,age,tm,g,gs,mp,fg,fga,fg%,...,orb,drb,trb,ast,stl,blk,tov,pf,pts,uuid
325,Reggie Miller,SG,31,IND,81,81,2966,552,1244,.444,...,53,233,286,273,75,25,166,172,1751,15a02eb5-28f3-4168-ae9d-d30ed736e98e

In [22]:
season_totals_2004

,player,pos,age,tm,g,gs,mp,fg,fga,fg%,...,orb,drb,trb,ast,stl,blk,tov,pf,pts,uuid
0,Shareef Abdur-Rahim,PF,28,POR,54,49,1867,337,670,.503,...,123,269,392,111,49,26,117,150,909,fe3dd58a-1354-44f3-8d09-e6c39cb1cca5
1,Cory Alexander,SG,31,CHA,16,1,201,16,49,.327,...,8,21,29,37,9,1,19,29,49,aec90717-ab44-4cfe-afb6-0feb8b6f9362
2,Malik Allen,PF,26,TOT,36,1,519,84,177,.475,...,40,59,99,18,9,22,18,53,194,6c881a9f-326a-4c7c-8b77-64040bbf30b8
3,Malik Allen,PF,26,MIA,14,0,248,35,76,.461,...,24,28,52,11,4,11,11,29,83,6c881a9f-326a-4c7c-8b77-64040bbf30b8
4,Malik Allen,PF,26,CHA,22,1,271,49,101,.485,...,16,31,47,7,5,11,7,24,111,6c881a9f-326a-4c7c-8b77-64040bbf30b8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
528,Qyntel Woods,SF,23,MIA,3,0,40,5,12,.417,...,2,4,6,0,4,0,2,6,10,83e3a6e4-f017-458b-b7a4-f67a4e2f9912
529,Metta World Peace,SF,25,IND,7,7,291,59,119,.496,...,8,37,45,22,12,6,17,27,172,670a19ff-960f-4b66-89c5-c438ef9dcd19
530,Dorell Wright,SF,19,MIA,3,0,27,3,11,.273,...,0,1,1,3,4,0,3,2,7,8d19fa58-5d7c-49eb-9712-a43a2d02db6d
531,Lorenzen Wright,C,29,MEM,80,77,2287,320,683,.469,...,177,436,613,87,58,69,100,251,771,bab51822-a357-43c7-956a-e988098dc9e7
532,Wang Zhizhi,C,27,MIA,20,0,92,17,36,.472,...,6,12,18,5,3,2,5,9,43,2f0a09c5-4a53-48d5-951d-09df02d44838

In [23]:
len(df_list)

26

In [24]:
season_totals_2004.head(15)

,player,pos,age,tm,g,gs,mp,fg,fga,fg%,...,orb,drb,trb,ast,stl,blk,tov,pf,pts,uuid
0,Shareef Abdur-Rahim,PF,28,POR,54,49,1867,337,670,.503,...,123,269,392,111,49,26,117,150,909,fe3dd58a-1354-44f3-8d09-e6c39cb1cca5
1,Cory Alexander,SG,31,CHA,16,1,201,16,49,.327,...,8,21,29,37,9,1,19,29,49,aec90717-ab44-4cfe-afb6-0feb8b6f9362
2,Malik Allen,PF,26,TOT,36,1,519,84,177,.475,...,40,59,99,18,9,22,18,53,194,6c881a9f-326a-4c7c-8b77-64040bbf30b8
3,Malik Allen,PF,26,MIA,14,0,248,35,76,.461,...,24,28,52,11,4,11,11,29,83,6c881a9f-326a-4c7c-8b77-64040bbf30b8
4,Malik Allen,PF,26,CHA,22,1,271,49,101,.485,...,16,31,47,7,5,11,7,24,111,6c881a9f-326a-4c7c-8b77-64040bbf30b8
5,Ray Allen,SG,29,SEA,78,78,3064,640,1494,.428,...,79,268,347,289,84,5,171,167,1867,d0df9ea6-dc69-4d3d-9311-41a1fdebad9c
6,Tony Allen,SG,23,BOS,77,34,1262,184,387,.475,...,85,136,221,64,76,24,77,156,492,917674b3-1b6e-48ed-8d3b-f9161c1ea734
7,Rafer Alston,PG,28,TOR,80,78,2717,403,974,.414,...,42,237,279,514,118,7,170,212,1136,ee905b13-ef4f-4bb4-9dd7-a8bf290c289a
8,Chris Andersen,C,26,NOH,67,2,1430,191,358,.534,...,137,273,410,71,14,100,64,144,513,1c7a2c3b-e319-4c55-9294-2550d654cf28
9,Derek Anderson,SG,30,POR,47,32,1239,152,391,.389,...,25,103,128,143,36,4,70,89,432,bf77e8c7-0dcd-4d9f-b189-9d1ad588d259
10,Kenny Anderson,PG,34,TOT,43,20,743,85,201,.423,...,24,64,88,103,33,0,49,87,203,a8644ea2-3e28-4207-98be-fda50363c248
11,Kenny Anderson,PG,34,ATL,39,20,717,81,190,.426,...,23,60,83,98,33,0,46,81,195,a8644ea2-3e28-4207-98be-fda50363c248
12,Kenny Anderson,PG,34,LAC,4,0,26,4,11,.364,...,1,4,5,5,0,0,3,6,8,a8644ea2-3e28-4207-98be-fda50363c248
13,Shandon Anderson,SF-SG,31,TOT,66,5,1171,98,217,.452,...,41,150,191,70,40,14,50,138,255,40966e4d-7253-436a-a7f9-3fb958f92711
14,Shandon Anderson,SG,31,NYK,1,0,20,0,2,.000,...,1,0,1,0,0,0,1,2,0,40966e4d-7253-436a-a7f9-3fb958f92711

In [25]:
def count_nulls(tables):
    for table in tables:
        print(f'{sum(table.isnull().sum())} nulls')

In [26]:
count_nulls(df_list)

0 nulls
0 nulls
0 nulls
0 nulls
0 nulls
0 nulls
0 nulls
0 nulls
0 nulls
0 nulls
0 nulls
0 nulls
0 nulls
0 nulls
0 nulls
0 nulls
0 nulls
0 nulls
0 nulls
0 nulls
0 nulls
0 nulls
0 nulls
0 nulls
0 nulls
0 nulls

In [27]:
season_totals_2004[season_totals_2004['player'].duplicated()]

,player,pos,age,tm,g,gs,mp,fg,fga,fg%,...,orb,drb,trb,ast,stl,blk,tov,pf,pts,uuid
3,Malik Allen,PF,26,MIA,14,0,248,35,76,.461,...,24,28,52,11,4,11,11,29,83,6c881a9f-326a-4c7c-8b77-64040bbf30b8
4,Malik Allen,PF,26,CHA,22,1,271,49,101,.485,...,16,31,47,7,5,11,7,24,111,6c881a9f-326a-4c7c-8b77-64040bbf30b8
11,Kenny Anderson,PG,34,ATL,39,20,717,81,190,.426,...,23,60,83,98,33,0,46,81,195,a8644ea2-3e28-4207-98be-fda50363c248
12,Kenny Anderson,PG,34,LAC,4,0,26,4,11,.364,...,1,4,5,5,0,0,3,6,8,a8644ea2-3e28-4207-98be-fda50363c248
14,Shandon Anderson,SG,31,NYK,1,0,20,0,2,.000,...,1,0,1,0,0,0,1,2,0,40966e4d-7253-436a-a7f9-3fb958f92711
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515,Aaron Williams,C,33,TOR,23,4,165,15,36,.417,...,10,19,29,2,1,3,6,45,36,f01bd8ac-7c4a-48e8-8480-b319dbe8bacd
517,Eric Williams,SG,32,NJN,21,21,739,87,185,.470,...,28,67,95,42,16,2,34,80,265,20616e0d-ed38-4118-9459-4bd2d79e8bad
518,Eric Williams,SG,32,TOR,34,18,583,55,145,.379,...,16,61,77,50,22,2,26,67,159,20616e0d-ed38-4118-9459-4bd2d79e8bad
524,Corliss Williamson,PF,31,PHI,48,5,1056,194,417,.465,...,73,105,178,43,26,12,60,144,518,54d2cdae-41c5-4f0a-82c6-1bb15dabbaf1
525,Corliss Williamson,PF,31,SAC,24,4,471,79,167,.473,...,31,50,81,35,12,3,26,74,223,54d2cdae-41c5-4f0a-82c6-1bb15dabbaf1

In [28]:
season_totals_2004[season_totals_2004.duplicated(subset=['player'], keep='first') == False].reset_index(drop=True)

,player,pos,age,tm,g,gs,mp,fg,fga,fg%,...,orb,drb,trb,ast,stl,blk,tov,pf,pts,uuid
0,Shareef Abdur-Rahim,PF,28,POR,54,49,1867,337,670,.503,...,123,269,392,111,49,26,117,150,909,fe3dd58a-1354-44f3-8d09-e6c39cb1cca5
1,Cory Alexander,SG,31,CHA,16,1,201,16,49,.327,...,8,21,29,37,9,1,19,29,49,aec90717-ab44-4cfe-afb6-0feb8b6f9362
2,Malik Allen,PF,26,TOT,36,1,519,84,177,.475,...,40,59,99,18,9,22,18,53,194,6c881a9f-326a-4c7c-8b77-64040bbf30b8
3,Ray Allen,SG,29,SEA,78,78,3064,640,1494,.428,...,79,268,347,289,84,5,171,167,1867,d0df9ea6-dc69-4d3d-9311-41a1fdebad9c
4,Tony Allen,SG,23,BOS,77,34,1262,184,387,.475,...,85,136,221,64,76,24,77,156,492,917674b3-1b6e-48ed-8d3b-f9161c1ea734
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
420,Qyntel Woods,SF,23,MIA,3,0,40,5,12,.417,...,2,4,6,0,4,0,2,6,10,83e3a6e4-f017-458b-b7a4-f67a4e2f9912
421,Metta World Peace,SF,25,IND,7,7,291,59,119,.496,...,8,37,45,22,12,6,17,27,172,670a19ff-960f-4b66-89c5-c438ef9dcd19
422,Dorell Wright,SF,19,MIA,3,0,27,3,11,.273,...,0,1,1,3,4,0,3,2,7,8d19fa58-5d7c-49eb-9712-a43a2d02db6d
423,Lorenzen Wright,C,29,MEM,80,77,2287,320,683,.469,...,177,436,613,87,58,69,100,251,771,bab51822-a357-43c7-956a-e988098dc9e7
424,Wang Zhizhi,C,27,MIA,20,0,92,17,36,.472,...,6,12,18,5,3,2,5,9,43,2f0a09c5-4a53-48d5-951d-09df02d44838

In [31]:
def remove_duplicates(tables):
    cleaned_df_list = []
    for i in range(len(tables)):
        years = [year for year in range(1996, 2022)]
        var_name = f'season_totals_{years[i]}'
        globals()[var_name] = tables[i][tables[i].duplicated(subset=['player'], keep='first') == False].reset_index(drop=True)
        cleaned_df_list.append(globals()[var_name])
        globals()[var_name].to_csv(f'../updated_datasets/season_totals/{var_name}.csv')
        print(f'{var_name} is done!')
    return cleaned_df_list

In [32]:
cleaned_df_list = remove_duplicates(df_list)

season_totals_1996 is done!
season_totals_1997 is done!
season_totals_1998 is done!
season_totals_1999 is done!
season_totals_2000 is done!
season_totals_2001 is done!
season_totals_2002 is done!
season_totals_2003 is done!
season_totals_2004 is done!
season_totals_2005 is done!
season_totals_2006 is done!
season_totals_2007 is done!
season_totals_2008 is done!
season_totals_2009 is done!
season_totals_2010 is done!
season_totals_2011 is done!
season_totals_2012 is done!
season_totals_2013 is done!
season_totals_2014 is done!
season_totals_2015 is done!
season_totals_2016 is done!
season_totals_2017 is done!
season_totals_2018 is done!
season_totals_2019 is done!
season_totals_2020 is done!
season_totals_2021 is done!

In [33]:
def load_data():
    loaded_list = []
    for i in [year for year in range(1990, 2022)]:
        var_name = f'season_totals_{i}'
        table = pd.read_csv(f'../updated_datasets/season_totals/{var_name}.csv')
        globals()[var_name] = table[table.columns[1:]]
        globals()[var_name]['year'] = i
        globals()[var_name].to_csv(f'../updated_datasets/season_totals/{var_name}.csv')
        loaded_list.append(var_name)
    return loaded_list

In [34]:
load_data()

['season_totals_1990',
 'season_totals_1991',
 'season_totals_1992',
 'season_totals_1993',
 'season_totals_1994',
 'season_totals_1995',
 'season_totals_1996',
 'season_totals_1997',
 'season_totals_1998',
 'season_totals_1999',
 'season_totals_2000',
 'season_totals_2001',
 'season_totals_2002',
 'season_totals_2003',
 'season_totals_2004',
 'season_totals_2005',
 'season_totals_2006',
 'season_totals_2007',
 'season_totals_2008',
 'season_totals_2009',
 'season_totals_2010',
 'season_totals_2011',
 'season_totals_2012',
 'season_totals_2013',
 'season_totals_2014',
 'season_totals_2015',
 'season_totals_2016',
 'season_totals_2017',
 'season_totals_2018',
 'season_totals_2019',
 'season_totals_2020',
 'season_totals_2021']

In [35]:
season_totals_2021

,player,pos,age,tm,g,gs,mp,fg,fga,fg%,...,drb,trb,ast,stl,blk,tov,pf,pts,uuid,year
0,Precious Achiuwa,C,22,TOR,73,28,1725,265,603,0.439,...,327,473,82,37,41,84,151,664,278abde6-6a4e-429d-b90c-1a0bfd422b38,2021
1,Steven Adams,C,28,MEM,76,75,1999,210,384,0.547,...,411,760,256,65,60,115,153,528,02815787-f72f-4342-874d-4a5588d6e030,2021
2,Bam Adebayo,C,24,MIA,56,56,1825,406,729,0.557,...,427,564,190,80,44,148,171,1068,a0b335f7-8a52-4164-91c5-0090952103a4,2021
3,LaMarcus Aldridge,C,36,BRK,47,12,1050,252,458,0.550,...,185,258,42,14,47,44,78,607,8e44a15c-b4d5-4dfe-bdf7-b86931475b32,2021
4,Nickeil Alexander-Walker,SG,23,TOT,65,21,1466,253,680,0.372,...,150,187,156,46,23,93,103,692,e52882fd-5990-4be9-a1a3-8d307f3c3738,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
526,Thaddeus Young,PF,33,TOT,52,1,845,141,272,0.518,...,128,208,104,54,18,52,81,322,533ca18b-3cf2-4380-89bf-ea331753c585,2021
527,Trae Young,PG,23,ATL,76,76,2652,711,1544,0.460,...,234,284,737,72,7,303,128,2155,4567c890-b16c-40e3-a31d-30a2614a7ed0,2021
528,Omer Yurtseven,C,23,MIA,56,12,706,130,247,0.526,...,209,294,49,17,20,41,84,299,3e37b73e-76f8-4e59-a5a8-d3270154cd5b,2021
529,Cody Zeller,C,29,POR,27,0,355,51,90,0.567,...,75,125,22,8,6,19,56,140,593ab841-2293-44bd-aabe-fa8596fbfeb4,2021
530,Ivica Zubac,C,24,LAC,76,76,1852,310,495,0.626,...,427,644,120,36,77,114,203,785,336b75a2-39f8-4300-99a7-a50887820cd1,2021